site_name: How-to-Guides

theme: 
  name: material
  features: 
    - content.code.copy
  favicon: img/favicon.ico

markdown_extensions:
  - codehilite
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition
  - pymdownx.details


nav:
  - Host MkDocs project using GitHub Pages: index.md
  - Change the Favicon icon in MkDocs: fav.md


